/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package polyglot_module;

/**
 *
 * @author Nitin
 */
public class add_friends extends javax.swing.JFrame {

    /**
     * Creates new form add_friends
     */
    public add_friends() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_add_frnd = new javax.swing.JLabel();
        panel_add_frnd = new javax.swing.JPanel();
        txt_userid = new javax.swing.JTextField();
        lbl_uname = new javax.swing.JLabel();
        btn_continue = new javax.swing.JButton();
        lbl_userid = new javax.swing.JLabel();
        txt_uname = new javax.swing.JTextField();
        btn_skip = new javax.swing.JButton();
        lbl_img = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        lbl_add_frnd.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        lbl_add_frnd.setText("Add a friend");
        getContentPane().add(lbl_add_frnd);
        lbl_add_frnd.setBounds(20, 30, 110, 40);

        panel_add_frnd.setBackground(new java.awt.Color(0, 0, 0));
        panel_add_frnd.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        lbl_uname.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbl_uname.setForeground(new java.awt.Color(255, 255, 255));
        lbl_uname.setText("Username");

        btn_continue.setText("Continue");

        lbl_userid.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbl_userid.setForeground(new java.awt.Color(255, 255, 255));
        lbl_userid.setText("Email id");

        btn_skip.setText("Skip");

        javax.swing.GroupLayout panel_add_frndLayout = new javax.swing.GroupLayout(panel_add_frnd);
        panel_add_frnd.setLayout(panel_add_frndLayout);
        panel_add_frndLayout.setHorizontalGroup(
            panel_add_frndLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_add_frndLayout.createSequentialGroup()
                .addGroup(panel_add_frndLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_add_frndLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(panel_add_frndLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_userid, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panel_add_frndLayout.createSequentialGroup()
                                .addComponent(txt_uname, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addGroup(panel_add_frndLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lbl_uname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lbl_userid, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(panel_add_frndLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(btn_continue, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(btn_skip, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        panel_add_frndLayout.setVerticalGroup(
            panel_add_frndLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_add_frndLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(panel_add_frndLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_uname)
                    .addComponent(txt_uname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(panel_add_frndLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_userid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_userid))
                .addGap(18, 18, 18)
                .addGroup(panel_add_frndLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_continue)
                    .addComponent(btn_skip))
                .addGap(19, 19, 19))
        );

        getContentPane().add(panel_add_frnd);
        panel_add_frnd.setBounds(40, 90, 302, 150);
        getContentPane().add(lbl_img);
        lbl_img.setBounds(0, 0, 400, 300);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(add_friends.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(add_friends.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(add_friends.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(add_friends.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                add_friends add=new add_friends();
                add.setSize(400,300);
                add.setVisible(true);
                //new add_friends().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_continue;
    private javax.swing.JButton btn_skip;
    private javax.swing.JLabel lbl_add_frnd;
    private javax.swing.JLabel lbl_img;
    private javax.swing.JLabel lbl_uname;
    private javax.swing.JLabel lbl_userid;
    private javax.swing.JPanel panel_add_frnd;
    private javax.swing.JTextField txt_uname;
    private javax.swing.JTextField txt_userid;
    // End of variables declaration//GEN-END:variables
}
